services:
  - type: web
    name: beatapi
    runtime: docker
    repo: https://github.com/Beat-All-Repo/BeatAPI.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
