services:
  - type: web
    name: beatapi
    runtime: docker
    repo: https://github.com/Beat-All-Repo/BeatAPI.git
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANIWATCH_API_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: ANIWATCH_API_DEPLOYMENT_ENV
        value: docker
      - key: ANIWATCH_API_CORS_ALLOWED_ORIGINS
        value: "*"
      - key: ANIWATCH_API_WINDOW_MS
        value: 1800000
      - key: ANIWATCH_API_MAX_REQS
        value: 100
      - key: ANIWATCH_API_S_MAXAGE
        value: 60
      - key: ANIWATCH_API_STALE_WHILE_REVALIDATE
        value: 30
      - key: ANIWATCH_API_HOSTNAME
        value: beatapi.onrender.com
      - key: TATAKAI_ADMIN_API_SECRET
        value: your_actual_secret_here
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
